apiVersion : apps/v1
kind: Deployment
metadata:
  name: "bikepack-6dc6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "bikepack-6dc6"
  template:
    metadata:
      labels:
        app: "bikepack-6dc6"
    spec:
      containers:
        - name: "bikepack-6dc6"
          image: "bikepack.azurecr.io/bikepack"
          ports:
          - containerPort: 1234