apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: service-area-ingress
spec:
  routes:
    - match: PathPrefix(`/api/service-areas`)
      kind: Rule
      services:
        - name: service-area-service
          port: 1234
      middlewares:
        - name: allow-headers
        - name: forward-auth