apiVersion: v1
kind: Service
metadata:
    name: "bikepack-6dc6"
    labels:
        app: "bikepack-6dc6"
spec:
    type: LoadBalancer
    ports:
    - port: 1234
      targetPort: 1234
      protocol: TCP
      name: http
    selector:
        app: "bikepack-6dc6"