// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/service-areas": {
            "get": {
                "description": "gets all service-areas in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get all service-areas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.ServiceArea"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "creates a new service-area",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "create service-area",
                "parameters": [
                    {
                        "description": "Add service-area",
                        "name": "service-area",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.BodyCreateServiceArea"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseCreateServiceArea"
                        }
                    }
                }
            }
        },
        "/api/service-areas/{id}": {
            "get": {
                "description": "gets a service-area from the system by its ID",
                "produces": [
                    "application/json"
                ],
                "summary": "get service-area",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service-area id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ServiceArea"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Area": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        }
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.ServiceArea": {
            "type": "object",
            "properties": {
                "area": {
                    "$ref": "#/definitions/domain.Area"
                },
                "id": {
                    "type": "integer"
                },
                "identifier": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "riderCoverage": {
                    "type": "integer"
                }
            }
        },
        "dto.BodyCreateServiceArea": {
            "type": "object",
            "properties": {
                "area": {
                    "$ref": "#/definitions/domain.Area"
                },
                "id": {
                    "type": "integer"
                },
                "identifier": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.ResponseCreateServiceArea": {
            "type": "object",
            "properties": {
                "area": {
                    "$ref": "#/definitions/domain.Area"
                },
                "id": {
                    "type": "integer"
                },
                "identifier": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "riderCoverage": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
