definitions:
  domain.Area:
    properties:
      coordinates:
        items:
          items:
            items:
              type: number
            type: array
          type: array
        type: array
      type:
        type: string
    type: object
  domain.ServiceArea:
    properties:
      area:
        $ref: '#/definitions/domain.Area'
      id:
        type: integer
      identifier:
        type: string
      name:
        type: string
      riderCoverage:
        type: integer
    type: object
  dto.BodyCreateServiceArea:
    properties:
      area:
        $ref: '#/definitions/domain.Area'
      id:
        type: integer
      identifier:
        type: string
      name:
        type: string
    type: object
  dto.ResponseCreateServiceArea:
    properties:
      area:
        $ref: '#/definitions/domain.Area'
      id:
        type: integer
      identifier:
        type: string
      name:
        type: string
      riderCoverage:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/service-areas:
    get:
      consumes:
      - application/json
      description: gets all service-areas in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.ServiceArea'
            type: array
      summary: get all service-areas
    post:
      consumes:
      - application/json
      description: creates a new service-area
      parameters:
      - description: Add service-area
        in: body
        name: service-area
        required: true
        schema:
          $ref: '#/definitions/dto.BodyCreateServiceArea'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseCreateServiceArea'
      summary: create service-area
  /api/service-areas/{id}:
    get:
      description: gets a service-area from the system by its ID
      parameters:
      - description: Service-area id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ServiceArea'
      summary: get service-area
swagger: "2.0"
