name: "Deploy cluster"

on: 
  push:
    tags:
      - v*
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml
  build:
    needs: [tests]
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bikepack_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: bikepack.azurecr.io
        container-registry-username: ${{ secrets.acr_bikepack_username }}
        container-registry-password: ${{ secrets.acr_bikepack_password }}
        secret-name: bikepackdockerauth
        
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/ingress.yml
          manifests/deployment.yml
          manifests/service.yml
        images: |
          bikepack.azurecr.io/bikepack/service-area-service:latest
        imagepullsecrets: |
          bikepackdockerauth
