name: "Deploy cluster"

on: 
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/run-tests.yml
  build:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      -
        name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: ACR Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_BIKEPACK_USERNAME }}
          password: ${{ secrets.ACR_BIKEPACK_PASSWORD }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_bikepack_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: bikepack.azurecr.io
        container-registry-username: ${{ secrets.acr_bikepack_username }}
        container-registry-password: ${{ secrets.acr_bikepack_password }}
        secret-name: bikepackdockerauth
        
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          manifests/ingress.yml
          manifests/deployment.yml
          manifests/service.yml
        images: |
          bikepack.azurecr.io/bikepack/service-area-service:latest
        imagepullsecrets: |
          bikepackdockerauth
