name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build containers
      run: docker-compose -f ./docker-compose.test.yaml build
      
    - name: Run tests
      run: docker-compose -f ./docker-compose.test.yaml run test-service-area-service gotest -v -p=1 ./...

    - name: Cleanup containers
      run: docker-compose -f ./docker-compose.test.yaml down
